import { EMPTY, BLOCK } from '../utils/consts'

export default [
  [BLOCK, BLOCK, BLOCK, BLOCK, 1, BLOCK, BLOCK, BLOCK, BLOCK],
  [BLOCK, BLOCK, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, BLOCK, BLOCK],
  [2, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 2],
  [EMPTY, EMPTY, EMPTY, EMPTY, BLOCK, EMPTY, EMPTY, EMPTY, EMPTY],
  [EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
  [EMPTY, EMPTY, EMPTY, BLOCK, EMPTY, BLOCK, EMPTY, EMPTY, EMPTY],
  [1, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 1],
  [BLOCK, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, BLOCK],
  [BLOCK, BLOCK, BLOCK, EMPTY, 2, EMPTY, BLOCK, BLOCK, BLOCK],
]
